name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lavrenkot/playwright-build-tests:latest
      
    - name: Run Playwright tests in Docker
      run: |
          docker run --rm \
            -e BASE_URL="$BASE_URL" \
            -e HTTP_CREDENTIALS_USERNAME="$HTTP_CREDENTIALS_USERNAME" \
            -e HTTP_CREDENTIALS_PASSWORD="$HTTP_CREDENTIALS_PASSWORD" \
            lavrenkot/playwright-build-tests:latest
